function Aviso(){
<alert("VOCÊ VIOLOU PRINCÍPIOS DE SEGURANÇA DE REDE.\n\nESTÁ COMPROVADO QUE HOUVE FURTO DE PARTES DO CÓDICO DE PROGRAMAS PARA WEB IMAGEN PROPRIETÁRIA."\n
"A COMUNIDADE LINUX REPUDIA ESTE TIPO DE ATITUDE."\n\n"NO BRASIL O TRÁFEGO CONFIRMADO COMO INVASÃO DE REDE COM MANIPULAÇÃO DE IMAGEM PELO PROTOCOLO UDP É CRIME PREVISTO NO CODIGO PENAL BRASILEIRO."\n"Alterações feitas na Lei penal sancionada pelo ministro do Supremo Tribunal Federal: Dias Tofoli.");
}
 
