GitHub Packages/Trabalhar com um registro do GitHub Packages/Registro do Apache Maven
Trabalhando com o repositório do Apache Maven
Você pode configurar o Apache Maven para publicar pacotes no GitHub Packages e usar pacotes armazenados no GitHub Packages como dependências em um projeto Java.

Neste artigo
Autenticar-se no GitHub Packages
Observação

O GitHub Packages dá suporte apenas à autenticação que usa um personal access token (classic). Para saber mais, confira Gerenciar seus tokens de acesso pessoal.

Você precisa de um token de acesso para publicar, instalar e excluir pacotes privados, públicos e internos.

Você pode usar um personal access token (classic) para se autenticar no GitHub Packages ou na API do GitHub. Ao criar um personal access token (classic), você pode atribuir diferentes escopos de token, dependendo da sua necessidade. Para obter mais informações sobre escopos relacionados a pacotes para personal access token (classic), confira Sobre permissões para o GitHub Packages.

Para efetuar a autenticação em um registro do GitHub Packages dentro de um fluxo de trabalho de GitHub Actions, você pode utilizar:

GITHUB_TOKEN para publicar pacotes associados ao repositório do fluxo de trabalho.
Um personal access token (classic) com pelo menos escopo read:packages para instalar pacotes associados a outros repositórios privados (GITHUB_TOKEN pode ser usado se o repositório receber acesso de leitura ao pacote. Confira, Configurando o controle de acesso e visibilidade de um pacote).
Para obter mais informações sobre o GITHUB_TOKEN usado em fluxos de trabalho do GitHub Actions, confira Usar GITHUB_TOKEN para autenticação em fluxos de trabalho.

Autenticar com um personal access token
Você precisa usar um personal access token (classic) com os escopos apropriados para publicar e instalar pacotes no GitHub Packages. Para saber mais, confira Introdução ao GitHub Packages.

Você pode autenticar para GitHub Packages com Apache Maven, editando seu arquivo ~/.m2/settings.xml para incluir seu personal access token (classic). Crie um novo arquivo ~/.m2/settings.xml se um não existir.

Na tag servers, adicione uma tag filho server com uma id, substituindo USERNAME pelo nome de usuário do GitHub e TOKEN pelo seu personal access token.

Na tag repositories, configure um repositório mapeando a id do repositório para a id adicionada à tag server que contém suas credenciais. Substitua OWNER pelo nome da conta pessoal ou organização proprietária do repositório. Como não é permitido usar letras maiúsculas, é preciso usar letras minúsculas no nome do proprietário do repositório, mesmo que o nome do usuário ou da organização no GitHub contenha letras maiúsculas.

Caso deseje interagir com vários repositórios, adicione cada repositório para separar os filhos do repository na tag repositories, mapeando a id de cada um para as credenciais contidas na marca servers.

O GitHub Packages dá suporte às versões de SNAPSHOT do Apache Maven. Para usar o repositório do GitHub Packages para baixar artefatos SNAPSHOT, habilite SNAPSHOTS no POM do projeto de consumo ou no arquivo ~/.m2/settings.xml.

<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      http://maven.apache.org/xsd/settings-1.0.0.xsd">

  <activeProfiles>
    <activeProfile>github</activeProfile>
  </activeProfiles>

  <profiles>
    <profile>
      <id>github</id>
      <repositories>
        <repository>
          <id>central</id>
          <url>https://repo.maven.apache.org/maven2</url>
        </repository>
        <repository>
          <id>github</id>
          <url>https://maven.pkg.github.com/RIBEIROEDNILSON@1234/CAMPANHA</url>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
          <name>CAMPANHA</name>
        </repository>
      </repositories>
    </profile>
  </profiles>

  <servers>
    <server>
      <id>github</id>
      <username>ribeiroednilson1234</username>
      <password>GitHub2@2025</password>
    </server>
  </servers>
</settings>

<project>
    <build>
    <plugins>
        <plugin>
            <groupId>org.eclipse.jkube</groupId>
            <artifactId>kubernetes-maven-plugin</artifactId>
            <version>1.18.2</version> <!-- Verifique a versão mais recente -->
            <executions>
                <execution>
                    <goals>
                        <goal>resource</goal>
                        <goal>build</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>


 <dependencies>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-streams</artifactId>
            <version>4.0.0</version>
        </dependency>
    </dependencies>

</project>

<project>
    
    <dependencies>
        <dependency>
            <alterReplicaLogDirs(Map<TopicPartitionReplica,String>
                 Properties props = new Properties();
                 props.put(AdminClientConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");

             try (Admin admin = Admin.create(props)) {
                    String topicName = "my-topic";
                    int partitions = 12;
                    short replicationFactor = 3;
               // Create a compacted topic
                CreateTopicsResult result = admin.createTopics(Collections.singleton(
                    new NewTopic(topicName, partitions, replicationFactor)
                   .configs(Collections.singletonMap(TopicConfig.CLEANUP_POLICY_CONFIG, TopicConfig.CLEANUP_POLICY_COMPACT))));

               // Call values() to get the result for a specific topic
               KafkaFuture<Void> future = result.values().get(topicName);

               // Call get() to block until the topic creation is complete or has failed
               // if creation failed the ExecutionException wraps the underlying cause.
               future.get();
        }
            </alterReplicaLogDirs>
        </dependecy>
    </dependencies>
</project>
process.roles:
nó.id
O ID do nó associado às funções que este processo desempenha quando process.roles não está vazio. Esta é uma configuração necessária ao executar no modo KRaft.

Tipo:	int
Padrão:	
Valores válidos:	[0,...]
Importância:	alto
Modo de atualização:	somente leitura

corretor.id
O ID do corretor para este servidor.

Tipo:	int
Padrão:	-1
Valores válidos:	
Importância:	alto
Modo de atualização:	somente leitura

controlador.ouvinte.nomes
Uma lista separada por vírgulas dos nomes dos ouvintes usados ??pelo controlador. Isso é necessário ao se comunicar com o quórum do controlador; o broker sempre usará o primeiro ouvinte dessa lista.

Tipo:	corda
Padrão:	nulo
Valores válidos:	
Importância:	alto
Modo de atualização:	somente leitura

ouvintes
Lista de Ouvintes - Lista separada por vírgulas de URIs que escutaremos e os nomes dos ouvintes. Se o nome do ouvinte não for um protocolo de segurança, ele listener.security.protocol.maptambém deve ser definido.
Os nomes e números de porta dos ouvintes devem ser únicos, a menos que um ouvinte seja um endereço IPv4 e o outro seja um endereço IPv6 (para a mesma porta).
Especifique o nome do host como 0.0.0.0 para vincular a todas as interfaces.
Deixe o nome do host em branco para vincular à interface padrão.
Exemplos de listas de ouvintes válidas:
PLAINTEXT://myhost:9092,SSL://:9091
CLIENT://10.1.2.5:9092,REPLICATION://localhost:9093
PLAINTEXT://10.1.2.25:9092,SSL://[::1]:9092

Tipo:	corda
Padrão:	TEXTO SIMPLES://:9092
Valores válidos:	
Importância:	alto
Modo de atualização:	por corretor

void calloc(stdlib.h ) init(servlet){
service(){
do.get(browser)
request("e.g, Get "#"")response("e.g, Post "#"") in{ ci/cd: on {
true{@PostMapping("ff02::1:ffxx:xxxx){"e.g, * / r / n / t *"}};
j.query(".css"){$.code("background-color", "#000000" )};
System.out.println("response", "servlet")
}}}}
