<project>

    <dependencies>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>4.0.0</version>
        </dependency>
    </dependencies>

</project>

<project>

    <dependencies>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-streams</artifactId>
            <version>4.0.0</version>
        </dependency>
    </dependencies>

</project>

<project>
    
    <dependencies>
        <dependency>
            <alterReplicaLogDirs(Map<TopicPartitionReplica,String>
                 Properties props = new Properties();
                 props.put(AdminClientConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");

             try (Admin admin = Admin.create(props)) {
                    String topicName = "my-topic";
                    int partitions = 12;
                    short replicationFactor = 3;
               // Create a compacted topic
                CreateTopicsResult result = admin.createTopics(Collections.singleton(
                    new NewTopic(topicName, partitions, replicationFactor)
                   .configs(Collections.singletonMap(TopicConfig.CLEANUP_POLICY_CONFIG, TopicConfig.CLEANUP_POLICY_COMPACT))));

               // Call values() to get the result for a specific topic
               KafkaFuture<Void> future = result.values().get(topicName);

               // Call get() to block until the topic creation is complete or has failed
               // if creation failed the ExecutionException wraps the underlying cause.
               future.get();
        }
            </alterReplicaLogDirs>
        </dependecy>
    </dependencies>
</project>
process.roles:
nó.id
O ID do nó associado às funções que este processo desempenha quando process.roles não está vazio. Esta é uma configuração necessária ao executar no modo KRaft.

Tipo:	int
Padrão:	
Valores válidos:	[0,...]
Importância:	alto
Modo de atualização:	somente leitura

corretor.id
O ID do corretor para este servidor.

Tipo:	int
Padrão:	-1
Valores válidos:	
Importância:	alto
Modo de atualização:	somente leitura

controlador.ouvinte.nomes
Uma lista separada por vírgulas dos nomes dos ouvintes usados ??pelo controlador. Isso é necessário ao se comunicar com o quórum do controlador; o broker sempre usará o primeiro ouvinte dessa lista.

Tipo:	corda
Padrão:	nulo
Valores válidos:	
Importância:	alto
Modo de atualização:	somente leitura

ouvintes
Lista de Ouvintes - Lista separada por vírgulas de URIs que escutaremos e os nomes dos ouvintes. Se o nome do ouvinte não for um protocolo de segurança, ele listener.security.protocol.maptambém deve ser definido.
Os nomes e números de porta dos ouvintes devem ser únicos, a menos que um ouvinte seja um endereço IPv4 e o outro seja um endereço IPv6 (para a mesma porta).
Especifique o nome do host como 0.0.0.0 para vincular a todas as interfaces.
Deixe o nome do host em branco para vincular à interface padrão.
Exemplos de listas de ouvintes válidas:
PLAINTEXT://myhost:9092,SSL://:9091
CLIENT://10.1.2.5:9092,REPLICATION://localhost:9093
PLAINTEXT://10.1.2.25:9092,SSL://[::1]:9092

Tipo:	corda
Padrão:	TEXTO SIMPLES://:9092
Valores válidos:	
Importância:	alto
Modo de atualização:	por corretor

